image: debian:buster

test:
    script:
      - apt-get update
      - apt-get install -y cmake g++
      - apt-get install -y valgrind
      - apt-get install -y libsparsehash-dev libnauty2-dev liblz4-dev
      - mkdir build
      - cd build
      - cmake -DENABLE_ASSERTS=YES -DMOTIVO_OVERFLOW_SAFE=YES ..
      - make
      - ctest
      - ctest -T memcheck
      - make package
      - dpkg -i Motivo-*-Linux.deb
