# This is a sample build configuration for C++.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: debian:stretch-backports

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -y cmake g++
          - apt-get install -y libsparsehash-dev libopenblas-dev liblapacke-dev libnauty2-dev liblz4-dev
          - mkdir build
          - cd build
          - cmake -DENABLE_ASSERTS=YES -DMOTIVO_OVERFLOW_SAFE=YES ..
          - make
          - ctest
          - ctest -T memcheck
          - make package
          - dpkg -i Motivo-*-Linux.deb
